# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1d29612bf60f58b5877806b003345d842644113a92880d28c05a10901291393e4e8596d1a39daeed2b5fc93e32529e58ab7d7c0e8e45c01f31b01ef43469db3

test:
  secret_key_base: b7a0e62b90dc693e1bc4a97761ed159c5f9847fce0573dd463ca8da05d56f1c8fde94297f99d1c3160d56c1bab29bcc8295a11c8a2cba35e389b777a98ef693a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
